version: '3'
services:
  tfg:
    build: .
    command: python3 /web/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data:/data
      - ./web/db.sqlite3:/web/db.sqlite3
    ports:
      - 80:8000