# Generated by Django 3.0.6 on 2020-05-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=12)),
                ('port', models.IntegerField()),
                ('key', models.CharField(max_length=250)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
